#!/bin/bash

set -e

source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh

echo "---> Enabling s2i support in httpd24 image"

config_s2i
cp -Rf /usr/locl/*.html ./
DATE= `date "+%F"`
echo $DATE "hisame" >> ./info.html
echo "---> Installing application source"

# Fix source directory permissions
fix-permissions ./

process_extending_files ${HTTPD_APP_ROOT}/src/httpd-post-assemble/ ${HTTPD_CONTAINER_SCRIPTS_PATH}/post-assemble/

# Fix source directory permissions
fix-permissions ./

